version: 1.0.{build}

configuration:
	- Release
	- Debug

platform: x86

matrix:
	project: MonoTest.DirectX/MonoTest.DirectX.csproj
	project: MonoTest.DirectX/MonoTest.OpenGL.csproj

build:
	project: $(project_name)
	verbosity: minimal

test: off