version: 1.0.{build}

configuration:
  - Release
  - Debug

platform: x86

install: 
  - ps: >-
      Invoke-WebRequest  "https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/MonoGameSetup.exe" -OutFile "c:\application\data\MonoGameSetup.exe"
      Start-Process -Wait -FilePath "c:\application\data\MonoGameSetup.exe"

environment:
  matrix:
    - project_name: MonoTest.DirectX/MonoTest.DirectX.csproj
    - project_name: MonoTest.OpenGL/MonoTest.OpenGL.csproj

build:
  project: $(project_name)
  verbosity: minimal

test: off

matrix:
  fast_finish: true