version: 1.0.{build}

configuration:
  - Release
  - Debug


install:
- ps: >-
    $source = "https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/MonoGameSetup.exe"

    $output = "MonoGameSetup.exe"

    Start-FileDownload $source

    Start-Process -Wait -FilePath $output /S

build:
  project: MonoTest.sln
  parallel: true
  verbosity: minimal

test: off

matrix:
  fast_finish: true