version: 1.0.{build}

configuration:
  - Release
  - Debug

platform: x86

install:
- ps: >-
    $source = "https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/MonoGameSetup.exe"

    $output = "MonoGameSetup.exe"

    Start-FileDownload $source

    Start-Process -Wait -FilePath $output -ArgumentsList "/S" -Wait

environment:
  matrix:
    - project_name: MonoTest.DirectX/MonoTest.DirectX.csproj
    - project_name: MonoTest.OpenGL/MonoTest.OpenGL.csproj

build:
  project: $(project_name)
  verbosity: minimal

test: off

matrix:
  fast_finish: true