version: 1.0.{build}

configuration:
  - Release
  - Debug

platform: x86

install:
- ps: >-
    $source = "https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/MonoGameSetup.exe"

    $output = "MonoGameSetup.exe"

    Start-FileDownload $source

    Start-Process -Wait -FilePath $output /S

environment:
  matrix:
    - project_name: MonoTest.Another
    - project_name: MonoTest.DirectX
    - project_name: MonoTest.OpenGL
        platform: Any CPU

build:
  project: $(project_name)/$(project_name).csproj
  verbosity: minimal

test: off

matrix:
  fast_finish: true