version: 1.0.{build}

install:
- ps: >-
    $source = "https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/MonoGameSetup.exe"

    $output = "MonoGameSetup.exe"

    Start-FileDownload $source

    Start-Process -Wait -FilePath $output /S

environment:
  matrix:

  # DirectX Job
  - job_name: DirectX
    project_name: MonoTest.DirectX
    configuration: 
      Debug
      Release
    platform: x86

  # OpenGL Job
  - job_name: OpenGL
    project_name: MonoTest.OpenGL
    configuration: 
      Debug
      Release
    platform: AnyCPU

matrix:
  fast_finish: true

build:
  project: $(project_name)/$(project_name).csproj
  parallel: true
  verbosity: minimal

test: off
