version: 1.0.{build}

configuration:
  - Release
  - Debug

platform: x86

environment:
  matrix:
    - project_name: MonoTest.DirectX/MonoTest.DirectX.csproj
    - project_name: MonoTest.OpenGL/MonoTest.OpenGL.csproj

build:
  project: $(project_name)
  verbosity: minimal

test: off

matrix:
  fast_finish: true
